version: '2.4'

services:
  app:
    image: tech:dev  # либо image, либо build
#    build:
#      context: .
#    container_name: app
    ports:
      - "${HTTP_HOST_PORT}:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: always
    volumes:
      - ./appData:/app/fileStorage

  db:
    image: 'postgres:13-alpine'
    container_name: db
    #    ports:
    #      - "5432:5432"
    expose: # если наружу не надо
      - 5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - ./dbData:/var/lib/postgresql/data
