version: '3.8'

services:
  app:
    #    image: tech:dev  # либо image, либо build
    build:
      context: .
    container_name: app
    ports:
      - "${HTTP_HOST_PORT}:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/db_example
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - ./appData:/app/fileStorage

  db:
    container_name: mysql
    image: "mysql:latest"
    environment:
      -  MYSQL_DATABASE=${MYSQL_DATABASE}
      -  MYSQL_USER=${MYSQL_USER}
      -  MYSQL_PASSWORD=${MYSQL_PASSWORD}
      -  MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    #    expose:
    #      - "3306"
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql


