version: '3.8'

services:
#  adminer:
#    container_name: adminer
#    image: adminer:4
#    ports:
#      - "${ADMINER_PORT}:8080"
#    restart: always
  app:
    #    image: tech:dev  # либо image, либо build
    build:
      context: .
    #    container_name: app
    ports:
      - "${HTTP_HOST_PORT}:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_example
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - ./appData:/app/fileStorage

  db:
    image: percona:5.6
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql


